# Generated by cmd/build. Edit palette.json instead.
set -g @miel-bg "#0C0E13"
set -g @miel-text "#DED3BC"
set -g @miel-dim "#6F552C"
set -g @miel-gold "#E6A817"
set -g @miel-gold-hot "#FFC857"
set -g @miel-cream "#FFF1CC"
set -g @miel-good "#79B87A"
set -g @miel-warn "#E58B32"
set -g @miel-critical "#D96C64"
set -g @miel-surface "#1E2A38"

set -g status on
set -g status-interval 1
set -g status-justify left
set -g status-style "bg=#{@miel-bg},fg=#{@miel-text}"
set -g status-left-length 100
set -g status-right-length 100
set -g status-left "#[fg=#{@miel-gold},bg=#{@miel-bg},bold] #S #[fg=#{@miel-dim},bg=#{@miel-bg}]/ "
set -g window-status-separator ""
set -g @miel-window-label "#{?#{==:#I,1},𝖆,#{?#{==:#I,2},𝖇,#{?#{==:#I,3},𝖈,#{?#{==:#I,4},𝖉,#{?#{==:#I,5},𝖊,#{?#{==:#I,6},𝖋,#{?#{==:#I,7},𝖌,#{?#{==:#I,8},𝖍,#{?#{==:#I,9},𝖎,#{?#{==:#I,10},𝖏,#{?#{==:#I,11},𝖐,#{?#{==:#I,12},𝖑,#{?#{==:#I,13},𝖒,#{?#{==:#I,14},𝖓,#{?#{==:#I,15},𝖔,#{?#{==:#I,16},𝖕,#{?#{==:#I,17},𝖖,#{?#{==:#I,18},𝖗,#{?#{==:#I,19},𝖘,#{?#{==:#I,20},𝖙,#{?#{==:#I,21},𝖚,#{?#{==:#I,22},𝖛,#{?#{==:#I,23},𝖜,#{?#{==:#I,24},𝖝,#{?#{==:#I,25},𝖞,#{?#{==:#I,26},𝖟,#I}}}}}}}}}}}}}}}}}}}}}}}}}}"
setw -g window-status-format "#[fg=#{@miel-dim},bg=#{@miel-bg}]│#[fg=#{@miel-text},bg=#{@miel-bg}] #{E:@miel-window-label} #W "
setw -g window-status-current-format "#[fg=#{@miel-gold},bg=#{@miel-surface}]│> #[bold]#{E:@miel-window-label} #W #[nobold]<#[fg=#{@miel-dim},bg=#{@miel-bg}]"
set -g status-right "#[fg=#{@miel-dim},bg=#{@miel-bg}]⛬ #[fg=#{@miel-gold-hot},bg=#{@miel-bg},bold]#h #[fg=#{@miel-dim},bg=#{@miel-bg}]| #[fg=#{@miel-cream},bg=#{@miel-bg},bold]%H:%M#[fg=#{@miel-dim},bg=#{@miel-bg}] ⠶ #[fg=#{@miel-text},bg=#{@miel-bg}]%d-%b "
set -g pane-border-style "fg=#{@miel-dim}"
set -g pane-active-border-style "fg=#{@miel-gold}"
set -g message-style "bg=#{@miel-gold},fg=#{@miel-bg},bold"
set -g mode-style "bg=#{@miel-gold-hot},fg=#{@miel-bg},bold"
