#!/bin/sh
# Generated by cmd/build. Edit shared/palette.json instead.

index=0
reset='\033[0m'
separator="\\033[38;2;111;85;44m"
prompt_start=
prompt_end=
case ${POSH_SHELL-} in
  zsh) prompt_start='%{' ; prompt_end='%}' ;;
  bash) prompt_start='\[' ; prompt_end='\]' ;;
esac
escape() { printf '%s%b%s' "$prompt_start" "$1" "$prompt_end"; }
add() {
  case $((index % 5)) in
    0) color="\\033[38;2;111;85;44m" ;;
    1) color="\\033[38;2;152;116;58m" ;;
    2) color="\\033[38;2;166;106;44m" ;;
    3) color="\\033[38;2;230;168;23m" ;;
    4) color="\\033[38;2;255;200;87m" ;;
  esac
  if [ "$index" -ne 0 ]; then
    escape "$separator"
    printf ' / '
    escape "$reset"
  fi
  escape "$color"
  printf '%s %s' "$1" "$2"
  escape "$reset"
  index=$((index + 1))
}
version() { "$@" 2>/dev/null || printf 'nover'; }
go_version() {
  command -v go >/dev/null 2>&1 && go version 2>/dev/null | awk '{print $3}' || printf 'nover'
}
java_version() {
  command -v java >/dev/null 2>&1 && java -version 2>&1 | awk -F '"' '/version/ { print $2; exit }' || printf 'nover'
}
python_version() {
  command -v python3 >/dev/null 2>&1 && version python3 --version || version python --version
}
qml_version() {
  if command -v qml >/dev/null 2>&1; then
    qml --version 2>&1 | awk 'NR == 1 { print $NF; exit }'
  elif command -v qmake >/dev/null 2>&1; then
    qmake -query QT_VERSION 2>/dev/null
  else
    printf 'nover'
  fi
}

[ -f package.json ] && add '' "$(version node --version)"
[ -f tsconfig.json ] && add '' "$(version tsc --version)"
[ -f go.mod ] && add '' "$(go_version)"
if [ -f pom.xml ] || [ -f build.gradle ] || [ -f build.gradle.kts ]; then
  add '' "$(java_version)"
fi
if [ -f pyproject.toml ] || [ -f requirements.txt ] || [ -f Pipfile ] || [ -f setup.py ]; then
  add '' "$(python_version)"
fi
if [ -f .qmlproject ] || [ -f ./*.qml ]; then
  add 'QML' "$(qml_version)"
fi

dir=$PWD
root=
while :; do
  if [ -f "$dir/package.json" ]; then
    root=$dir
    break
  fi
  [ "$dir" = / ] && break
  dir=${dir%/*}
  [ -n "$dir" ] || dir=/
done
if [ -n "$root" ] && { [ -f "$root/turbo.json" ] || [ -f "$root/turbo.jsonc" ]; }; then
  turbo_version=
  if [ -x "$root/node_modules/.bin/turbo" ]; then
    turbo_version=$("$root/node_modules/.bin/turbo" --version 2>/dev/null | head -n 1)
  elif command -v turbo >/dev/null 2>&1; then
    turbo_version=$(turbo --version 2>/dev/null | head -n 1)
  elif command -v node >/dev/null 2>&1; then
    turbo_version=$(node -e 'const p=require(process.argv[1]); console.log((p.devDependencies||{}).turbo||(p.dependencies||{}).turbo||"")' "$root/package.json" 2>/dev/null)
  fi
  [ -n "$turbo_version" ] && add '' "$turbo_version"
fi
[ -f yarn.lock ] && add '' "$(version yarn --version)"
[ -f package-lock.json ] && add '' "$(version npm --version)"
[ -f pnpm-lock.yaml ] && add '' "$(version pnpm --version)"
exit 0
