#!/bin/sh
# Generated by cmd/build. Edit shared/palette.json instead.

active_index=0
requested_index=${1-}
# Preserve spacing between text segments.
separator='⁠ '
selected() { [ "$requested_index" = "$active_index" ]; }
skip() { active_index=$((active_index + 1)); }
clean_version() {
  printf '%s' "$1" | sed -E 's/^(v|Version[[:space:]]+|go|Python[[:space:]]+)//'
}
add() {
  display_version=$(clean_version "$2")
  [ "$active_index" -eq 0 ] || printf '%s' "$separator"
  printf '%s %s' "$1" "$display_version"
  active_index=$((active_index + 1))
}
version() { "$@" 2>/dev/null || printf 'nover'; }
go_version() {
  command -v go >/dev/null 2>&1 && go version 2>/dev/null | awk '{print $3}' || printf 'nover'
}
java_version() {
  command -v java >/dev/null 2>&1 && java -version 2>&1 | awk -F '"' '/version/ { print $2; exit }' || printf 'nover'
}
python_version() {
  command -v python3 >/dev/null 2>&1 && version python3 --version || version python --version
}
qml_version() {
  if command -v qml >/dev/null 2>&1; then
    qml --version 2>&1 | awk 'NR == 1 { print $NF; exit }'
  elif command -v qmake >/dev/null 2>&1; then
    qmake -query QT_VERSION 2>/dev/null
  else
    printf 'nover'
  fi
}

if [ -f package.json ]; then
  selected && add '' "$(version node --version)" || skip
fi
if [ -f tsconfig.json ]; then
  selected && add '' "$(version tsc --version)" || skip
fi
if [ -f go.mod ]; then
  selected && add '' "$(go_version)" || skip
fi
if [ -f pom.xml ] || [ -f build.gradle ] || [ -f build.gradle.kts ]; then
  selected && add '' "$(java_version)" || skip
fi
if [ -f pyproject.toml ] || [ -f requirements.txt ] || [ -f Pipfile ] || [ -f setup.py ]; then
  selected && add '' "$(python_version)" || skip
fi
if [ -f .qmlproject ] || [ -f ./*.qml ]; then
  selected && add 'QML' "$(qml_version)" || skip
fi

dir=$PWD
  root=
  while :; do
    if [ -f "$dir/package.json" ]; then
    root=$dir
      break
    fi
    [ "$dir" = / ] && break
    dir=${dir%%/*}
    [ -n "$dir" ] || dir=/
  done
if [ -n "$root" ] && { [ -f "$root/turbo.json" ] || [ -f "$root/turbo.jsonc" ]; }; then
  if selected; then
    turbo_version=
    if [ -x "$root/node_modules/.bin/turbo" ]; then
      turbo_version=$("$root/node_modules/.bin/turbo" --version 2>/dev/null | head -n 1)
    elif command -v turbo >/dev/null 2>&1; then
      turbo_version=$(turbo --version 2>/dev/null | head -n 1)
    elif command -v node >/dev/null 2>&1; then
      turbo_version=$(node -e 'const p=require(process.argv[1]); console.log((p.devDependencies||{}).turbo||(p.dependencies||{}).turbo||"")' "$root/package.json" 2>/dev/null)
    fi
    [ -n "$turbo_version" ] && add '' "$turbo_version"
  else
    skip
  fi
fi
if [ -f yarn.lock ]; then
  selected && add '' "$(version yarn --version)" || skip
fi
if [ -f package-lock.json ]; then
  selected && add '' "$(version npm --version)" || skip
fi
if [ -f pnpm-lock.yaml ]; then
  selected && add '' "$(version pnpm --version)" || skip
fi
exit 0
